### ISSUE TITLE
same dot return

### ISSUE THREAD

**Issue by arpecop** [WinterCore/react-pattern-lock#1]
Great job really and probably my question ruins the intention of "pattern-locks" but it will be great to have repeatable pattern or return to previous dot
Thanks

**Comment by WinterCore** [comment]
Hi
Could you explain more ?
What I understood is that you want the ability to activate the same point multiple times ? correct me if I'm wrong.
Thanks :)

**Comment by arpecop** [comment]
Thanks for replying, 
The pattern I am looking is something similar to swipe-keyboards 
`[0,1,0,2,1]`
if that makes sense

**Comment by WinterCore** [comment]
I think its possible to add it as an additional option.
Thanks for the suggestion.

**Comment by arpecop** [comment]
Great, I wish I was "problem-solver" like you regarding coding 👍 
If you allow me I have few more suggestions:

- rounded corners in the beginning and the end of the point-line
- onDotConnect handler

**Comment by WinterCore** [comment]
@arpecop Your suggestions have been added.
Check the (```allowOverlapping```, ```connectorRoundedCorners``` and ```onDotConnect```) props.

Thanks again.
