### ISSUE TITLE
PatternLock.tsx TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by ezesali** [WinterCore/react-pattern-lock#14]
Show error when rendering tag <PatternLock/>

**Comment by WinterCore** [comment]
Hey.

@ezesali Could you provide more info on how to reproduce the error, a code snippet for example?

You could also fork the [CodeSandbox](https://codesandbox.io/s/n5j7knjo54) demo, Replace the code there with yours, and provide a link

**Comment by ezesali** [comment]
Oh sory. Maybe i forgot to insert some attributes. Its working!! Thanks!

**Comment by WinterCore** [comment]
Okay. That's great.
