### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by anasfaraz** [WinterCore/react-pattern-lock#17]
how to start the index from 1 not from 0

**Comment by WinterCore** [comment]
Hey.

If you're talking about the pattern representation you could do something like this.
```js
this.state.path.map(x => x + 1) // just loop over the path points and add 1
```
but if you're trying to store the path representation in a database or something don't forget to subtract the 1 you added before comparing/using it.

**Comment by anasfaraz** [comment]
Thank u so much for that
