### ISSUE TITLE
Cant connect points when I change the size to 4x4 (and higher)

### ISSUE THREAD

**Issue by erniberni1611** [WinterCore/react-pattern-lock#26]
I got another issue in my project with the pattern.
One component is the pattern in 3x3, that works perfectly fine.
Another component starts with the pattern in 4x4, that works fine too, but when I change the size of it, I cant connect the points anymore.
What could be the reason for this behavior?

Which part of my code could possibly help to find my error?

**Comment by WinterCore** [comment]
Hey.

Yeah, I just found out that the function that calculates the position of the points doesn't account for scrolling. I'll fix it and get back to you.

**Comment by WinterCore** [comment]
Hey, @erniberni1611.

The issue should be fixed in 2.0.9. Make sure to update and let me know if it works for you.

**Comment by erniberni1611** [comment]
Hello @WinterCore.
I've just tested it, now it is possible to connect all points even if the pattern is 15x15.
------
I did notice one more thing, though. When I enlarge the pattern to 15x15, the actual line is shifted a bit, so it's not perfect at the point where the mouse cursor is.

But if I make my browser window smaller and then make it bigger again, it works perfectly.

I recorded my screen with this pattern behaviour so you can see exactly what I mean.

Could this be due to my CSS settings?


https://user-images.githubusercontent.com/20776021/107017430-66f93080-679f-11eb-8793-d78bb3d6b6d7.mp4

**Comment by WinterCore** [comment]
Hey, @erniberni1611.

Thank you so much for reporting this, and I really appreciate the video you provided.

The issue should be fixed in [2.0.10](https://www.npmjs.com/package/react-pattern-lock/v/2.0.10)

**Comment by erniberni1611** [comment]
Hey @WinterCore.
I tried now everything again and for now it all works perfect. 
Thank you very much for your work!
