### ISSUE TITLE
Pattern of more than 4 may not solve properly

### ISSUE THREAD

**Issue by Bouloute** [WinterCore/react-pattern-lock#29]
Hi,

First of all your package is really well done, I love how it flows perfectly and has no lagging time.

I've been running into an issue. When I use a size of more than 3, and I'm drawing a line from right to left and skipping more than 2 dots at a time (Overlapping set to false), the output is not what would be expected.

Here's an example to help:
On a first row or a size of 5 ->
0 1 2 3 4 

If i drag 0 to 4 without touching 1,2 and 3, the output is as expected 0-1-2-3-4
If i drag 4 to 0 without touching 1,2 and 3, I would expect the output to by 4-3-2-1-0
Instead the output is 4-1-2-3-0

**Comment by WinterCore** [comment]
Hey @Bouloute 
> First of all your package is really well done, I love how it flows perfectly and has no lagging time.
Thank you. I'm glad you liked it.

Regarding the issue.
Good catch I've never actually tested this. maybe I'll add some tests in the future.

Thank you for reporting this I'll work on a fix soon.

**Comment by WinterCore** [comment]
Resolved in [v2.0.11](https://github.com/WinterCore/react-pattern-lock/releases/tag/v2.0.11)

Thanks again.
