### ISSUE TITLE
Issue with picking and scrolled window

### ISSUE THREAD

**Issue by sebastien-schneider** [WinterCore/react-pattern-lock#33]
Hi,
thank you for your library, very usefull.

I got an issue with the point picking when window has scrollbar (vertical one is simple to reproduce),
at the first render and before any resize, the mouse pointer position is offset by some pixels over the displayed points.
(I can't really understand why but when the window is resized, all the interaction behaviors are ok).

I wonder if the `onResize` from the `PatternLock.tsx`, should really do that : `setPosition({ x : left + window.scrollX, y : top + window.scrollY }) ;` because when you reuse the position in the `checkCollision` you still apply the window scroll offset on the position. It looks like something strange to me.. 

My proposal would be to implement `onResize` with : `setPosition({ x : left , y : top });`

Your guess ?

thanks for your help,
cheers, Sebastien.

**Comment by WinterCore** [comment]
Hey.

I think you may be right, I don't actually remember the code that well 😁 so I can't tell you for sure.
Feel free to submit a PR with a fix. if not I'll take a look at it myself whenever I have time.

Thanks.

**Comment by sebastien-schneider** [comment]
Here you are ;-)

I spent some time on it .. you've to keep the coordinate calculation with scroll information, but the issue is about the wrapper element position update that is updated only on resize event. You have to update it on scroll event also and the behavior is really fine on scrolled window this way.

I let you check that

**Comment by WinterCore** [comment]
Resolved in #35
