### ISSUE TITLE
Can this work with React-Native?

### ISSUE THREAD

**Issue by prodoxx** [WinterCore/react-pattern-lock#5]
It would be great if this worked with React-Native.

**Comment by WinterCore** [comment]
Hi
I don't think a react component can be made for both react and react-native
Wouldn't you need to convert all tags to their react-native ?
correct me if I'm wrong.

**Comment by prodoxx** [comment]
Yeah, you're right. I found one for react-native: https://github.com/AudyOdi/react-native-android-pattern-lock-screen. I'll combine your logic with his to create a usable React-Native component. 

Thanks, man. I'll give you credit if I use any of your code.

**Comment by WinterCore** [comment]
Anytime
