### ISSUE TITLE
onChange is being invoked on every click

### ISSUE THREAD

**Issue by yoavmmn** [WinterCore/react-pattern-lock#8]
The onChange function is being invoked on every click, anywhere on the window.
I'm trying to use this component and update the pattern to redux and the server, but this issue causes performance issues.

**Comment by WinterCore** [comment]
Hi
I don't understand what you mean by that ```onChange``` is being invoked on every click, It's the ```onRelease``` that gets called on every click (mouseup) event which in turn calls the ```onChange``` after checking that there's at least 1 pattern point selected.
Can you elaborate more please ?
Thanks.

**Comment by yoavmmn** [comment]
What I mean is that the function provided to `onChange` prop is being called even when I click on other elements, not just the lock pattern.

**Comment by WinterCore** [comment]
I wasn't able to reproduce this, I might be doing something wrong.
Could you please reproduce it in a [codesandbox](https://codesandbox.io) or upload the code on github

**Comment by yoavmmn** [comment]
You can see what I mean [here](https://codesandbox.io/s/nervous-newton-1jhuv).
After you enter the correct pattern, everything you click on will invoke the `onChange` function.

**Comment by WinterCore** [comment]
You're right, This issue occurs only if you use the ```freeze``` prop.
Even though #9 Fixes the issue, it raises another issue. Adding the release event listeners on the wrapper will cause issues if the user releases the mouse button outside the wrapper (the mouse would still be connected to the last pattern point even when the user is not holding the mouse button)
The issue has been addressed in 1.4.1.
Thanks for reporting this.
